# Generated by Django 5.0.6 on 2024-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='-', max_length=20)),
                ('subject', models.CharField(default='-', max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('year', models.IntegerField(default=0)),
                ('years_old', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Class',
            },
        ),
    ]
