# Generated by Django 5.0.6 on 2024-07-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('crId', models.AutoField(default='0', primary_key=True, serialize=False)),
                ('quota', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Classroom',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(default='-', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='crId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='my_app.classroom'),
        ),
        migrations.AddField(
            model_name='class',
            name='tId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher'),
        ),
    ]
