# Generated by Django 5.0.6 on 2024-07-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_classroom_teacher_class_quota_class_crid_class_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=20)),
                ('parent_name', models.CharField(default='-', max_length=20)),
                ('hp', models.CharField(default='-', max_length=10)),
                ('parent_hp', models.CharField(default='-', max_length=10)),
                ('years_old', models.IntegerField(default=0)),
                ('school', models.CharField(default='-', max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(default='-', max_length=1000)),
                ('address', models.CharField(default='-', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
