# Generated by Django 5.0.6 on 2024-07-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.class')),
                ('sId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.students')),
            ],
        ),
    ]
