# Generated by Django 5.0.6 on 2024-07-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher'),
        ),
        migrations.AlterModelTable(
            name='enrolled',
            table='Enrolled',
        ),
    ]
