# Generated by Django 5.0.6 on 2024-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_class_category_alter_class_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_name',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
    ]
