# Generated by Django 5.0.6 on 2024-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_classroom_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='remark',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
