# Generated by Django 5.0.6 on 2024-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_enrolled_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='remark',
            field=models.TextField(default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='remark',
            field=models.TextField(default='-', max_length=1000, null=True),
        ),
    ]
