# Generated by Django 5.0.6 on 2024-09-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_category_teacher_line_teacher_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='remark',
            new_name='remarks',
        ),
    ]
