# Generated by Django 5.0.6 on 2024-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_rename_remark_students_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
