# Generated by Django 5.0.6 on 2024-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_enrolled_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='eId',
            field=models.IntegerField(default=0),
        ),
    ]
