# Generated by Django 5.0.6 on 2024-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_enrolled_eid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='id',
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='eId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
