# Generated by Django 5.0.6 on 2024-09-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_enrolled_id_alter_enrolled_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('cId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.class')),
                ('eId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.enrolled')),
                ('sId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.students')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
