# Generated by Django 5.0.6 on 2024-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='periods',
            field=models.IntegerField(default=2),
        ),
    ]
