# Generated by Django 5.0.6 on 2024-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_class_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='periods',
            field=models.IntegerField(default=1),
        ),
    ]
