# Generated by Django 5.0.6 on 2024-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_class_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='available',
            field=models.IntegerField(default=1),
        ),
    ]
