# Generated by Django 5.0.6 on 2024-09-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_class_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.IntegerField(default=1111, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('tId', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('semester', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.semester')),
            ],
            options={
                'db_table': 'Time',
            },
        ),
    ]
