# Generated by Django 5.0.6 on 2024-09-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_semester_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='showtime',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
