# Generated by Django 5.0.6 on 2024-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_time_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='time',
            name='showtime',
        ),
        migrations.AddField(
            model_name='time',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
