# Generated by Django 5.0.6 on 2024-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_rename_time_time_start_remove_time_showtime_time_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='semId',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='semester',
            new_name='semId',
        ),
        migrations.AddField(
            model_name='semester',
            name='real_year',
            field=models.IntegerField(default=111),
        ),
        migrations.AddField(
            model_name='semester',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
