# Generated by Django 5.0.6 on 2024-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_rename_semester_semester_semid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semText',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
