# Generated by Django 5.0.6 on 2024-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_semester_semtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('aId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='-', max_length=100, null=True)),
                ('password', models.CharField(default='-', max_length=100, null=True)),
                ('permission', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
