# Generated by Django 5.0.6 on 2024-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tId',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='my_app.teacher'),
        ),
    ]
