# Generated by Django 5.0.6 on 2024-09-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_alter_class_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher'),
        ),
    ]
